title: "Light Player Test Runner"
css:
  - css/core.src.css
  - css/header.src.css
  - css/info.src.css
  - css/playlist.src.css
  - css/social.src.css
  - css/stage.src.css
js:
  - js/lib/o.src.js
  - js/lib/o-events.src.js
  - js/lib/jquery-1.4.3.min.js
  - js/lib/api.min.js
  - specs/helpers/buttons.js
  
  - js/core.src.js
  - js/header.src.js
  - js/info.src.js
  - js/playlist.src.js
  - js/social.src.js
  - js/stage.src.js

  - specs/core.spec.js
  - specs/header.spec.js
  - specs/info.spec.js
  - specs/social.spec.js
  - specs/stage.spec.js
